# site相关配置
site_name: 雨下不停的wiki
site_description: '雨下不停个人Wiki'
site_author: 'lamber'

# github
repo_url: https://github.com/LamberMa/lamber.github.io.git
repo_name: lamber/mkdocs-material

theme:
  # 指定使用material主题
  name: material
  custom_dir: overrides
  # 禁用google font
  font: false
  icon:
    repo: fontawesome/brands/github
  # 颜色方案
  palette:
    # scheme是整个主题的颜色，slate是暗色，default是亮色
    # primary这个是整个导航bar的颜色
    # accent是影响一些强调属性颜色的，比如说超链接鼠标放上去的颜色，按键颜色，滚动条颜色等等
    scheme: default
    primary: indigo
    accent: red
  # 设置网站的语言，默认是en
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    # 自动展开左侧所有的子菜单，默认我现在用不到
    # - navigation.expand
    # 快速返回顶层按钮
    - navigation.top
    # 将目录在左侧展开
    # - toc.integrate

plugins:
  - search
  # - minify:
  #     minify_html: true
  # - git-revision-date-localized:
  #     type: iso_datetime

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - abbr
  - attr_list
  - def_list
  - footnotes
  # 允许为html添加meta数据
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  # 代码高亮
  - pymdownx.highlight:
      use_pygments: true
      # 显示行号
      linenums: true
      linenums_style: pymdownx-inline
  # 该扩展允许代码块中嵌套其他代码块
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: leops-china
      repo: ansible-wiki
  - pymdownx.mark
  - pymdownx.smartsymbols
  # 允许从其他文件插入内容或者从其他常规文本中插入内容
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

nav:
  - 主页:
    - 常用连接: index.md
  - Go开发:
    - Go库学习: mds/go/pkgs/index.md
      #- 'net/http': mds/go/pkgs/net/http/index.md
    - Go知识点学习:
      - Go基础:
        - '01. Golang环境搭建': mds/go/basic/golanginstall/index.md
        - '02. 数据类型': mds/go/basic/datatype/index.md
        - '03. 流程控制': mds/go/basic/flowcontrol/index.md
        - '04. 格式化输出': mds/go/basic/format/index.md
        - 'Go关键字': mds/go/basic/关键字/index.md
        - 'Go Type详解': mds/go/basic/gotype/index.md
        - 'Go测试': mds/go/basic/go测试/index.md
        - '接口': mds/go/basic/接口/index.md
      - Go进阶:
        - '1. 项目开发规范': 
          - '1. 规范简介': mds/go/advanced/开发规范/规范简介/index.md
          - '2. 编写优雅Go项目': mds/go/advanced/开发规范/如何编写优雅的Go项目/index.md
        - '2. 设计模式':
          - '1. 简介': mds/go/advanced/设计模式/简介/index.md
          - '2. 创建型模式': mds/go/advanced/设计模式/创建者模式/index.md
        - '3. RPC':
          - '1. RPC简介': mds/go/advanced/rpc/1-rpc简介/index.md
        - '4. 权限管理':
          - 'Casbin':
            - '1. Casbin介绍': mds/go/advanced/permission/casbin/casbin介绍/index.md
    - Go并发:
      - '1. 并发简介': mds/go/concurrency/01-并发编程/01-并发编程初识/index.md
      - '2. Goroutine': mds/go/concurrency/01-并发编程/02-goroutine/index.md
      - '3. Channel': mds/go/concurrency/01-并发编程/03-channel/index.md

    - GoGin:
      - "1. Gin简介": mds/go/gin/1-gin框架初识/index.md
    - Go应用构建:
      - "1. Log日志":
        - "zap": mds/go/app/log/zap/zap.md
      - "2. 命令行构建":
        - "flag": mds/go/app/command/flag/flag.md
        - "pflag": mds/go/app/command/pflag/index.md
      - "3. 配置解析": mds/go/app/config/viper.md
    - Go速查表:
      - Json/Map/struct互转: mds/go/速查表/json-map-struct/index.md
  - 运维监控:
    - Prometheus:
      - 1. 安装: 
        - Prometheus安装: mds/monitor/prometheus/安装配置/install/index.md
        - PrometheusOperator:
          - 'PrometheusOperator介绍': mds/monitor/prometheus/operator/operator介绍/describe.md
      - 2. 监控配置:
        - Target配置: mds/monitor/prometheus/target/index.md
        - Rules规则: 
          - 记录规则: mds/monitor/prometheus/rules/recordrules/index.md
          - 告警规则: mds/monitor/prometheus/rules/alertrules/index.md
      - 3. Exporters:
        - 1. SNMP监控:
          - 'SNMP Exporter': mds/monitor/prometheus/exporters/SNMPExporter/SNMPExporter/index.md
          - 'Config生成器': mds/monitor/prometheus/exporters/SNMPExporter/configGenerator/index.md
        - 2. BlackBoxExporter: mds/monitor/prometheus/exporters/BlackBoxExporter/index.md
        - 3. NodeExporter: mds/monitor/prometheus/exporters/NodeExporter/index.md
        - 4. PingExporter: mds/monitor/prometheus/exporters/PingExporter/index.md
        - 99.自定义Exporter: 
          - 如何编写Exporter: mds/monitor/prometheus/exporters/自定义Exporter/编写exporter.md
      - 4. 监控报警:
        - 1. Alertmanager: mds/monitor/prometheus/alert/alertmanager/index.md
      - 5. VitoriaMetrics:
        - 1. vm简介: mds/monitor/prometheus/victoriametrics/vm简介/index.md

      - 监控规范:
        - "默认告警策略": mds/monitor/prometheus/监控理论/默认告警策略/index.md
    - Zabbix:
      - Zabbix宏: mds/monitor/zabbix/zabbix中的宏/index.md
      - Zabbix遇到的各种坑: mds/monitor/zabbix/zabbix坑/index.md
    - 常用:
      - '监控故障模拟': mds/monitor/常用/监控故障模拟/index.md
  - Linux运维:
    - Shell编程:
      - Shell重定向: mds/linux/shell/shell重定向/index.md
      - Shell中的括号: mds/linux/shell/shell中的括号/index.md
      - Sed: mds/linux/shell/sed/index.md
    - Git: 
      - "0. Git常见错误": mds/linux/git/00-git常见错误/index.md
      - "1. Git初步使用": mds/linux/git/01-git初步使用/index.md
      - "2. Git对象模型": mds/linux/git/02-git对象模型/index.md
      - "3. 常用场景处理": mds/linux/git/03-常用场景处理/index.md
    - 虚拟化:
      - KVM: mds/linux/虚拟化/kvm/index.md
    - 服务发现:
      - Consul:
        - Consul部署: mds/linux/ServiceDiscovery/Consul/consul_install/index.md
        - Consul ACL: mds/linux/ServiceDiscovery/Consul/acl/index.md
    - CI/CD:
      - Jenkins:
        - 记一次Win打包机的构建: mds/linux/cicd/jenkins/记一次win打包机的构建/index.md
        - 清理工作空间: mds/linux/cicd/jenkins/clean_workspace/index.md
    - 计算机基础:
      - 内存: mds/linux/base/memoryPage/index.md
    - 故障库:
      - 系统相关: 
        - VMFS_volume_member问题: mds/linux/troubleshooting/VMFS_volume_member问题/index.md
  - Kubernetes:
    - Docker:
      - Dockerfile详解: mds/k8s/docker/dockerfile详解/index.md
    - Kubernetes基础:
      - Service: mds/k8s/kubernetesBasic/service/index.md
      - 健康检查/探针: mds/k8s/kubernetesBasic/healthcheck/index.md
    - Helm:
      - Helm介绍: mds/k8s/helm/helm介绍/index.md
    - Kubernetes待定: mds/k8s/test.md
  - DNS运维:
    - BindDNS:
      - 0. 安装DNS:
        - 编译安装: mds/dns/bind/install/index.md
      - 1. 监控DNS: 
        - 使用Prometheus监控: mds/dns/bind/监控/Prometheus监控Bind/index.md
        - 自定义监控: mds/dns/bind/监控/自定义监控/index.md
      - 2. 区域间同步: mds/dns/bind/区域间同步/index.md
      - 3. 备份与恢复: mds/dns/bind/备份与恢复/index.md
      - 4. DNS劫持: mds/dns/bind/DNS劫持/index.md
      - 5. 最佳实践: mds/dns/bind/最佳实践/index.md
      - 6. 常见问题处理: mds/dns/bind/问题处理/index.md
      - 7. 自定义功能: mds/dns/bind/自定义功能/index.md
    - DNSmasq:
      - Dnsmasq基本使用: mds/dns/dnsmasq/基本使用/index.md
  - Material使用指南:
    - 使用文档: 
      - 颜色变更: mds/material/setup/changing_the_colors/index.md
    - Docker部署: mds/material/install/docker/index.md
    
